In [1]:
from sklearn.datasets import load_iris
from sklearn import tree
from six import StringIO # for data visualization
import numpy as np
import pydotplus # for data visualization

In [2]:
iris = load_iris()

In [3]:
iris.feature_names # This function will see the feature type which could understand as the column name for result in Ln6

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
iris.target_names # This function will show all the possible labels

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [5]:
iris.data[0] # Show the first training data set data

array([5.1, 3.5, 1.4, 0.2])

In [6]:
for i in range(len(iris.target)):
     # iris.target will show the label 
     # iris.data will show the features 
    print('Example: %d, label: %s, feature: %s' % (i, iris.target[i], iris.data[i]))
    

Example: 0, label: 0, feature: [5.1 3.5 1.4 0.2]
Example: 1, label: 0, feature: [4.9 3.  1.4 0.2]
Example: 2, label: 0, feature: [4.7 3.2 1.3 0.2]
Example: 3, label: 0, feature: [4.6 3.1 1.5 0.2]
Example: 4, label: 0, feature: [5.  3.6 1.4 0.2]
Example: 5, label: 0, feature: [5.4 3.9 1.7 0.4]
Example: 6, label: 0, feature: [4.6 3.4 1.4 0.3]
Example: 7, label: 0, feature: [5.  3.4 1.5 0.2]
Example: 8, label: 0, feature: [4.4 2.9 1.4 0.2]
Example: 9, label: 0, feature: [4.9 3.1 1.5 0.1]
Example: 10, label: 0, feature: [5.4 3.7 1.5 0.2]
Example: 11, label: 0, feature: [4.8 3.4 1.6 0.2]
Example: 12, label: 0, feature: [4.8 3.  1.4 0.1]
Example: 13, label: 0, feature: [4.3 3.  1.1 0.1]
Example: 14, label: 0, feature: [5.8 4.  1.2 0.2]
Example: 15, label: 0, feature: [5.7 4.4 1.5 0.4]
Example: 16, label: 0, feature: [5.4 3.9 1.3 0.4]
Example: 17, label: 0, feature: [5.1 3.5 1.4 0.3]
Example: 18, label: 0, feature: [5.7 3.8 1.7 0.3]
Example: 19, label: 0, feature: [5.1 3.8 1.5 0.3]
Example: 2

In [7]:
# First we shoule split the data into training data set and testing data set
test_idx = [0, 50, 100] # 三种不同花的起始label

# Training data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis = 0)

# Testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

In [8]:
# Second use decision tree to training data
clf = tree.DecisionTreeClassifier()
clf = clf.fit(train_data, train_target)

In [9]:
test_target # This is the real test target

array([0, 1, 2])

In [10]:
clf.predict(test_data) # Our predict result

array([0, 1, 2])

In [11]:
# viz code
dot_data = StringIO()
tree.export_graphviz(clf, out_file = dot_data, feature_names = iris.feature_names, class_names = iris.target_names,
                     filled = True, rounded = True, impurity = False)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf("iris.pdf")


True

In [13]:
test_data[0],test_target[0]

(array([5.1, 3.5, 1.4, 0.2]), 0)

In [15]:
iris.feature_names, iris.target_names

(['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 array(['setosa', 'versicolor', 'virginica'], dtype='<U10'))